### ISSUE TITLE
Raspberry/kodi - Thomas Woo

### ISSUE THREAD

**Issue by smileorigin** [smileorigin/gittalk#1]
http://smileorigin.site:4000/2020/01/11/Raspberry/kodi/ 

 Installationhttp://www.kodiplayer.cn/course/2902.html https://beekc.top/2019/09/09/install-kodi-in-raspberry-pi/ 1sudo apt-get install kodi kodi-pvr-iptvsimple  iptvsimple 插件可以使 kodi 收看网络电视。在网络山可以下载到扒

**Comment by SMILEORIGIN** [comment]
test
